name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libgl1 \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xinput0 \
          libxcb-xfixes0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Start virtual display and run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: poetry run pytest



